// Code generated by ifacemaker; DO NOT EDIT.

package internal

import (
	"github.com/gofiber/fiber/v3"
)

// Controller describes methods, implemented by the http package.
type Handler interface {
	GetSongDetail() fiber.Handler
	CreateSong() fiber.Handler
	UpdateSong() fiber.Handler
	DeleteSong() fiber.Handler
}
